### ISSUE TITLE
lack of csv

### ISSUE THREAD

**Issue by MasterWall** [bhavuk0909/Kernel_SVM_Classification#1]
Excuse me,could you please tell me where is the 'Social_Network_Ads.csv' in your code?Thanks!

**Comment by bhavuk0909** [comment]
Apologies, Uploaded the required file.

**Comment by bhavuk0909** [comment]
> Excuse me,could you please tell me where is the 'Social_Network_Ads.csv' in your code?Thanks!

Apologies, Uploaded the required file.

**Comment by MasterWall** [comment]
OK,get it,thank you!
